### ISSUE TITLE
nameprep ProhibitedBidirectionalText

### ISSUE THREAD

**Issue by owenthewizard** [sfackler/rust-stringprep#11]
`예제.example.рф` seems to be a valid IDN (`xn--2j5b21b.example.xn--p1ai`), but nameprep fails with `ProhibitedBidirectionalText`. At first glance it would appear either nameprep is too strict to ToASCII is too lax - not sure which (if any) is correct...

**Comment by owenthewizard** [comment]
It also doesn't like emojis...

**Comment by owenthewizard** [comment]
Maybe we're using different standards - I'm using https://url.spec.whatwg.org/#idna

**Comment by sfackler** [comment]
As the documentation states, the nameprep function implements RFC 3491. That may not correspond exactly to the current IDNA rules.
